# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
permalink: /:year/:month/:day/:title.html
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: true
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 沙漠的博客

description: 生活、文艺与梦想
# gavatar头像及Favicon
gavatar: http://pic.yupoo.com/24plus/E2O4V5oL/medium.jpg
favicon: http://pic.yupoo.com/24plus/E2O4V5oL/medium.jpg

author:
  name: 沙漠
  email: sha_moon@126.com
  github: shamoon-cn
  twitter: 李应
  pinterest: shamoon-cn
  linkedin: shamoon-cn
  bio: 万里长空,一朝风月.
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
